name: Configure AWS Profiles

description: Configures multiple OIDC AWS Role Sessions as AWS config profiles.

branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  profiles:
    required: true
    description: 'YAML mapping of profiles to configure.'
  default-region:
    required: false
    description: 'Default AWS region to be used if not specified in a profile.'
    default: 'us-west-2'
  duration-seconds:
    required: false
    description: 'Duration, in seconds, of the role session for each profile. Each role must allow this duration in its MaxSessionDuration.'
    default: '3600'

runs:
  using: "composite"
  steps:
    - name: Get OIDC Token
      shell: bash
      env:
        ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
        ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
      run: bash "${{ github.action_path }}/scripts/get-oidc-token.sh"

    - name: Setup AWS Profiles
      shell: bash
      env:
        OIDC_TOKEN: ${{ env.OIDC_TOKEN }}
        PROFILES: ${{ inputs.profiles }}
        DEFAULT_REGION: ${{ inputs.default-region }}
        DURATION_SECONDS: ${{ inputs.duration-seconds }}
      run: bash "${{ github.action_path }}/scripts/configure-aws-profiles.sh"

    - name: Verify AWS Profiles
      shell: bash
      env:
        PROFILES: ${{ inputs.profiles }}
        DEFAULT_REGION: ${{ inputs.default-region }}
      run: bash "${{ github.action_path }}/scripts/verify-aws-profiles.sh"
